### ISSUE TITLE
Could not find resources

### ISSUE THREAD

**Issue by Danny1451** [rlwimi/wwwww#1]
hello, I built this tool  successfully, I try cmd like this
 './wwww meta -s 201 -v -y 2017' 
but i got the follow verbose :
Scraping /videos/wwdc2017 -- https://developer.apple.com
Scanning sessions in track: App Frameworks
Scraping 2017 session #201...could not find resources for 2017 session #201
Scanning sessions in track: Design
Scanning sessions in track: Developer Tools
Scanning sessions in track: Distribution
Scanning sessions in track: Featured
Scanning sessions in track: Graphics and Games
Scanning sessions in track: Media
Scanning sessions in track: System Frameworks

**Comment by rlwimi** [comment]
Thanks for bringing this to my attention. The breakage should be fixed in master now. 

Web scraping is fragile, and Apple did change the format of the session page slightly. I'd like to set up some CI to periodically run and catch this kind of situation sooner.
